version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - ecommerce-net

  order-service:
    container_name: order-service
    build:
      context: ./order-service
    env_file:
      - ./order-service/.env
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-net
    ports:
      - "3000:3000"  # asumsikan shipping-service juga listen di 3000


  shipping-service:
    container_name: shipping-service
    build:
      context: ./shipping-service
    env_file:
      - ./shipping-service/.env
    restart: unless-stopped
    depends_on:
      - rabbitmq
    networks:
      - ecommerce-net
    ports:
      - "3001:3001"  # asumsikan shipping-service juga listen di 3000


networks:
  ecommerce-net:
    driver: bridge
